### ISSUE TITLE
Web Design - Header Section

### ISSUE THREAD

**Issue by cecipaat** [wizelineacademy/wizelineacademy-academy-lms#24]
**User Story:**
(This card only covers visual design, deployable menu and functionality are documented in other ticket)

As a system user, I want the header of the Odoo.sh website to resemble the design of the WordPress website. I would like three hyperlinks on the right side and three on the left side of the header. 

**Story points:** TBD

**Acceptance Criteria:**

- [ ]  Hyperlinks/Main Menus in the Header are displayed according to the original design of WordPress.

Reference: ![Image](https://github.com/wizelineacademy/wizelineacademy-academy-lms/assets/61470730/23a6b257-8c2a-4fed-961a-2bb1d5285b74)

- [ ] "Work", "Insight", "About" & "Careers" deployable menu and Hyperlink redirecting are not covered in this ticket, no need for testing
- [ ] "Wizeline" Hyperlink should redirect to: https://www.wizeline.com/
- [ ] "Academy" Hyperlink should redirect to: https://academy.wizeline.com/
- [ ] "Contact" Hyperlink should redirect to: https://www.wizeline.com/contact/

- [ ]  Hyperlinks/Main Menus in the Sub-header are displayed according to the original design of WordPress.

![Image](https://github.com/wizelineacademy/wizelineacademy-academy-lms/assets/61470730/7ba7238d-0873-407f-abef-a2025c0d1000)

- [ ] "About" Hyperlink should redirect to: https://academy.wizeline.com/
- [ ] "Explore" Hyperlink is out of the scope and documented in another ticket
- [ ] "Start Learning" Hyperlink is out of the scope and documented in another ticket

- [ ]  "Join our Mailing List" button design should be displayed according to the original design of WordPress. Functionality is out of the scope and documented in another ticket

![Image](https://github.com/wizelineacademy/wizelineacademy-academy-lms/assets/61470730/009b652f-8a1d-49f2-9ff1-b3a7d9825bcb)

- [ ] A new dropdown menu, which we'll call 'My Account', should be located to the left of the 'Join Our Mailing List' button, according to the default menu enabled in Odoo.sh, where users can navigate to view their profile information. Functionality is out of the scope and documented in another ticket

**Subtasks Devs:** TBD

**Subtasks QA:** TBD

**Definition of Done:** 

- [x] Dev - Code Complete
- [x] QA - The code has been tested and functions correctly.
- [x] All the acceptance criteria are met
- [x] PM/PdM - The functionality meets user expectation.

**Comment by jjuarez2** [comment]
QA Testing PASSED. Moved to "Ready for Client Approval". 

For this card we have 2 pending items that are in "In Progress" 

https://github.com/wizelineacademy/wizelineacademy-academy-lms/issues/35
https://github.com/wizelineacademy/wizelineacademy-academy-lms/issues/39

Those cards are related to "Work" "Insights," "About,", "Careers" and "Join Our Mailing List" options that are not considered in this scope for this card and will be tested once those are Ready for QA.

@Vicodemo @cecipaat @paulinarias
