### ISSUE TITLE
Web Design -  "MyAccount" Menu placement

### ISSUE THREAD

**Issue by Vicodemo** [wizelineacademy/wizelineacademy-academy-lms#26]
**User Story:**
As a system user, I wish for the 'MyAccount' menu to be placed next to the 'Join our main list' button in the header to enhance site navigability.

**Story points:** TBD

**Acceptance Criteria:**

- [ ] The visual presentation of the 'MyAccount' menu should be placed on the right side of the  'Join our main list' button for a cohesive and aesthetically pleasing layout.
- [ ] The placement of the 'MyAccount' menu next to the 'Join our main list' button is consistent across different web browsers.
- [ ] The placement of the 'MyAccount' menu next to the 'Join our main list' button design and behavior when deployed remains consistent across various screen sizes and devices, ensuring a responsive design.
- [ ] When logged in, The "MyAccount" menu should be identified by the name of the user and a row pointing down, indicating it is a deployable menu.
- [ ] When logged in. If clicking in the deployed menu - "MyAccount" link, the user should be redirected to the User's account details webpage. (The design and functionality of the user's account details webpage are outside the scope of this ticket and are documented in another one).
- [ ] When logged in. If clicking in the deployed menu - "Logout" link, the user should be redirected to the main Academy Web page: https://academy.wizeline.com/
- [ ] When logged out, The "MyAccount" menu should be identified as a link with the text "sign in" inviting the user to log in.
- [ ] When logged out. If clicking in the "sign in" link, user should be redirected to the Log in webpage (the log in webpage design and functionality is out of scope of this ticket and documented in another one)
- [ ] The 'MyAccount' deployable menu should function correctly, allowing users to navigate through their account-related options without any issues. (My Account webpage + log out) 

**Subtasks Devs:** TBD

**Subtasks QA:** TBD

**Definition of Done:**

- [ ]  Dev - Code Complete
- [ ]  QA - The code has been tested and functions correctly.
- [ ]  All the acceptance criteria are met
- [ ]  PM/PdM - The functionality meets user expectation.
