### ISSUE TITLE
Website Functionality - "Join Our Mailing List"  - Pop-up Form

### ISSUE THREAD

**Issue by cecipaat** [wizelineacademy/wizelineacademy-academy-lms#39]
- A pop-up with the form to request personal data should appear once you click on the "Join Our Mailing List" button.
- Field's form should be the same as the one of this reference: [](https://academy.wizeline.com/on-demand/ )

**User Story:**
As a website visitor, I want to be able to join the mailing list by clicking on the "Join Our Mailing List" button so that I can stay updated with the latest news and promotions from the company.

**Story Points:** TBD

**Acceptance Criteria:**

- [ ] When I visit the website, I should see a clearly visible "Join Our Mailing List" button on the homepage or any relevant page.
- [ ] When I click on the "Join Our Mailing List" button, a pop-up should appear with a form for me to enter my first name, last name, email address, gender, and country.
- [ ] The form should include clear instructions on subscribing and an option to agree to the company's terms and conditions and privacy policy. _--> @Vicodemo no lo veo en el campo de referencia, no se si dejarlo._
- [ ] After I enter my personal information and agree to the terms, the pop-up should close automatically, and I should receive a confirmation message that my subscription was successful.
- [ ] The confirmation message should also include information on how to unsubscribe from the mailing list if I wish to do so in the future.
- [ ] If I try to subscribe with an email address that is already on the mailing list, I should receive a message informing me that my email is already subscribed.
- [ ] If I enter an invalid email address, I should receive a message informing me that "There was an error. Please try again!" and prompting me to enter a valid email address.
- [ ] The pop-up should be easy to close if I decide not to subscribe at that time, either by clicking on a close button or by clicking outside of the pop-up.
- [ ] The entire process should be user-friendly, with clear instructions and no technical errors or glitches.

**Subtasks Devs:** TBD
**Subtasks QA:** TBD

**Definition of Done:**

- [ ] Dev - Code Complete
- [ ]  QA - The code has been tested and functions correctly.
- [ ]  All the acceptance criteria are met
- [ ]  PM/PdM - The functionality meets user expectations.
